---
title: "Data Cleaning of Peru 5 and Peru 6 Data"
author: "Daniela Munoz Lopez"
date: "2024-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Packages 
```{r}
#Load in packages that will be used throughout the markdown.
packages <- c("tidyverse", 
              "summarytools",
              "psych",
              #"reader",
              "tidyr",
              "lme4",
              "lmerTest",
              "jtools",
              "interactions",
              "rio",
              "ggplot2",
              "dplyr",
              "here")

#invisible(lapply(packages, install.packages, character.only = TRUE)) #install packages (only run once)
invisible(lapply(packages, library, character.only = TRUE)) #load the packages
```

#Load All Peru Data
```{r}
#load Peru data.
data_dir = dirname(dirname(here())) #Move out of "digitalstress_p5_p6" folder to the "Peru May 2019" folder

wave_folder <- "peru6" #Name of wave folder containing all Peru 6 data.

data_folder <- file.path(data_dir, "Waves", wave_folder, "projects", 
                         "data_prep", "data", "derivatives" ) #Path to the data within the wave_folder. Items in "" indicate the name of the folders within the data_dir & wave_folder.

file_name <- "Peru3_Peru4_Peru5_Peru6_all_withID_CLEAN_NO_IDENTIFIERS_ES_12.16.21.csv" #Name of the CSV containing the data. #USE CLEAN NO IDENTIFIERS

peru6 <- read.csv(here(data_folder,file_name), header = T, sep = ",", na.strings=c(""," ","NA")) #Load in the CSV using the file paths that were established above. 

as_tibble(peru6) #Convert the data frame into a tibble with class tbl_df. 

#Select only the data collected during Peru 5 and Peru 6
peru5_6 <- peru6 %>% 
  filter(wave == 'Peru 5' | wave == 'Peru 6') 

nrow(peru5_6) #Count rows of Peru 5 and Peru 6. N = 36,480

#check data
head(peru5_6, 20)
tail(peru5_6, 20)
```

#Filter Data
```{r}
#Select project specific columns
#NOTE: DSS items 6 and 18 were removed after initial Factor Analysis done by C.G.
peru5_6_relevant <- peru5_6 %>% 
  select(Peru3_4_5_6_ID, wave_ID, wave, session, exclude, group, 
         gender, birthmth, birthyr, 
         grade_2021, startdate_formatted, 
         promis_dep1:promis_dep8, promis_anx1:promis_anx4,
         dss1, dss2, dss3, dss4, dss5, dss7, dss8, dss9, dss10, 
         dss11, dss12, dss13, dss14, dss15, dss16, dss17,
         dss19, dss20)

nrow(peru5_6_relevant) # N = 36480 after selecting project specific rows

#Remove rows that met initial exclusion criteria (i.e., pilot trials).
peru5_6_exclusion <- peru5_6_relevant %>% 
  filter(exclude == 'no')

nrow(peru5_6_exclusion) # N = 36480 after selecting project specific rows

#Select relevant groups (based on those who completed all variables of interest)
peru5_6_group <- peru5_6_exclusion %>%
  filter(group == "Group3")

nrow(peru5_6_group) # N = 11,378 after selecting project specific groups (Group 3)

#Select relevant sessions (based on those who completed all variables of interest)
peru5_6_group_session  <- peru5_6_group %>%
  filter(session == "survey1_6a11" | session == "survey3_6a11")

nrow(peru5_6_group_session) # N = 6,450 after selecting project specific groups AND sessions (sessions 1 and 3)
```

#Relabel items (using dss1_V2 project as reference)
```{r}
#Relabel DSS
peru5_6_relabel<- peru5_6_group_session %>% 
      dplyr::mutate_at(c("dss1", "dss2", "dss3", "dss4",
                         "dss5", "dss7", "dss8", "dss9", "dss10", "dss11", 
                         "dss12" , "dss13", "dss14", "dss15", "dss16", "dss17", "dss19", "dss20"), 
                (~dplyr::recode(., "Nunca"='1',
                              "Casi Nunca"='2',
                              "Ocasionalmente" ='3',
                              "Ocasionalemente" ='3', #typo in Qualtrics spelling 
                              "Casi Siempre" ='4',
                              "Siempre" ='5' )))

#Relabel PROMIS ANX
peru5_6_relabel <- peru5_6_relabel %>%
    (dplyr::mutate_at(promis_anx1:promis_anx4),
     dplyr::recode(., ))


peru5_6_relabel$promis_anx


#Relabel PPROMIS DEP


```

#Make items numeric
```{r}

```

#Score items
##DSS
```{r}

```

##PMUM Anxiety
```{r}

```

##PMUM Depression
```{r}

```


























