---
title: "Data Cleaning of Peru 5 and Peru 6 Data"
author: "Daniela Munoz Lopez"
date: "2024-07-25"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Packages
```{r}
#Load in packages that will be used throughout the markdown.
packages <- c("tidyverse", 
              "summarytools",
              "psych",
              "reader",
              "tidyr",
              "lme4",
              "lmerTest",
              "jtools",
              "interactions",
              "rio",
              "ggplot2",
              "dplyr",
              "here")

#invisible(lapply(packages, install.packages, character.only = TRUE)) #install packages (only run once)
invisible(lapply(packages, library, character.only = TRUE)) #load the packages
```

#Load All Peru Data
```{r}
#load Peru data.
data_dir = dirname(dirname(here())) #Move out of "digitalstress_p5_p6" folder to the "Peru May 2019" folder

wave_folder <- "peru6" #Name of wave folder containing all Peru 6 data.

data_folder <- file.path(data_dir, "Waves", wave_folder, "projects", 
                         "data_prep", "data", "derivatives" ) #Path to the data within the wave_folder. Items in "" indicate the name of the folders within the data_dir & wave_folder.

file_name <- "Peru3_Peru4_Peru5_Peru6_all_withID_CLEAN_NO_IDENTIFIERS_ES_12.16.21.csv" #Name of the CSV containing the data. #USE CLEAN NO IDENTIFIERS

peru6 <- read.csv(here(data_folder,file_name), header = T, sep = ",", na.strings=c(""," ","NA")) #Load in the CSV using the file paths that were established above. 

as_tibble(peru6) #Convert the data frame into a tibble with class tbl_df. 

#Select only the data collected during Peru 5 and Peru 6
peru5_6 <- peru6 %>% 
  filter(wave == 'Peru 5' | wave == 'Peru 6') 

nrow(peru5_6) #Count rows of Peru 5 and Peru 6. N = 36,480

#check data
head(peru5_6, 20)
tail(peru5_6, 20)
```

#Filter & Preprocess Data
##Select relevant data
```{r}
#Select project specific columns
peru5_6_relevant <- peru5_6 %>% 
  select(Peru3_4_5_6_ID, wave_ID, wave, session, exclude, group, 
         gender, birthmth, birthyr, 
         grade_2021, startdate_formatted, 
         promis_dep1:promis_dep8, promis_anx1:promis_anx4,
         dss1, dss2, dss3, dss4, dss5, dss6, dss7, dss8, dss9, dss10, 
         dss11, dss12, dss13, dss14, dss15, dss16, dss17, dss18,
         dss19, dss20)

nrow(peru5_6_relevant) # N = 36480 after selecting project specific rows

#Remove rows that met initial exclusion criteria (i.e., pilot trials).
peru5_6_exclusion <- peru5_6_relevant %>% 
  filter(exclude == 'no')

nrow(peru5_6_exclusion) # N = 36480 after selecting project specific rows

#Select relevant groups (based on those who completed all variables of interest)
peru5_6_group <- peru5_6_exclusion %>%
  filter(group == "Group3")

nrow(peru5_6_group) # N = 11,378 after selecting project specific groups (Group 3)

#Select relevant sessions (based on those who completed all variables of interest)
peru5_6_group_session  <- peru5_6_group %>%
  filter(session == "survey1_6a11" | session == "survey3_6a11")

nrow(peru5_6_group_session) # N = 6,450 after selecting project specific groups AND sessions (sessions 1 and 3)
```

##Relabel items (using dss1_V2 project as reference)
```{r}
#Relabel DSS
peru5_6_relabel<- peru5_6_group_session %>% 
      dplyr::mutate_at(c("dss1", "dss2", "dss3", "dss4",
                         "dss5", "dss6", "dss7", "dss8", "dss9", "dss10", "dss11", 
                         "dss12" , "dss13", "dss14", "dss15", "dss16", "dss17", "dss18", "dss19", "dss20"), 
                (~dplyr::recode(., "Nunca"='1',
                              "Casi Nunca"='2',
                              "Ocasionalmente" ='3',
                              "Ocasionalemente" ='3', #typo in Qualtrics spelling 
                              "Casi Siempre" ='4',
                              "Siempre" ='5' )))

#Relabel PROMIS ANX
peru5_6_relabel <- peru5_6_relabel %>%
    dplyr::mutate_at(c("promis_anx1", "promis_anx2", "promis_anx3", "promis_anx4"),
     (~dplyr::recode(., "Nunca" = "1",
                        "Casi nunca" = "2",
                        "A veces" = "3",
                        "Muchas veces" = "4",
                        "Casi siempre" = "5")))

#Relabel PPROMIS DEP
peru5_6_relabel <- peru5_6_relabel %>%
    dplyr::mutate_at(c("promis_dep1", "promis_dep2", "promis_dep3", "promis_dep4",
                       "promis_dep5", "promis_dep6", "promis_dep7", "promis_dep8"),
     (~dplyr::recode(., "Nunca" = "1",
                        "Casi nunca" = "2",
                        "A veces" = "3",
                        "Muchas veces" = "4",
                        "Casi siempre" = "5")))
```

##Make items numeric
```{r}
#DSS
peru5_6_numeric <- peru5_6_relabel %>%
  mutate_at(vars(dss1:dss20), ~as.numeric(as.character(.)))

#PROMIS ANX
peru5_6_numeric <- peru5_6_numeric %>%
  mutate_at(vars(promis_anx1:promis_anx4), ~as.numeric(as.character(.)))

#PROMIS DEP
peru5_6_numeric <- peru5_6_numeric %>%
  mutate_at(vars(promis_dep1:promis_dep8), ~as.numeric(as.character(.)))
```

##Match DSS items across Peru 5 and Peru 6 data
###Adjust Peru 5
```{r}
#IMPORTANT NOTE: DSS items 1-20 were administered in Peru 5, however items 6 and 18 were removed after initial Factor Analysis done by C.G. DSS items 1-18 were therefore administered in Peru 6 to account for the removal of items 6 and 18.

#make DF with only Peru 5 data 
p5_only <- peru5_6_numeric[grepl("5_", peru5_6_numeric$wave_ID),]

#Check N
nrow(p5_only) #N for Peru 5 only = 3559

#drop items 6 and 18 
p5_only <- p5_only[, !(names(p5_only) %in% c("dss6", "dss18"))]
```

###Adjust Peru 6
```{r}
#make DF with only Peru 6 data 
p6_only <- peru5_6_numeric[grepl("6_", peru5_6_numeric$wave_ID),]

#Check N
nrow(p6_only) #N for Peru 6 only = 2891

#drop items 19 and 20 since there is no data for this
p6_only <- p6_only[, !(names(p6_only) %in% c("dss19", "dss20"))]

#Relabel responses to match Peru 5 DSS (no dss 6 or 18) NOTE: ONLY RUN ONCE TO AVOID ERROR.
p6_only <- p6_only %>%
  rename("dss7" = "dss6",
         "dss8" = "dss7",
         "dss9" = "dss8",
         "dss10" = "dss9",
         "dss11" = "dss10",
         "dss12" = "dss11",
         "dss13" = "dss12",
         "dss14" = "dss13",
         "dss15" = "dss14",
         "dss16" = "dss15",
         "dss17" = "dss16",
         "dss19" = "dss17",
         "dss20" = "dss18")
```


###Combine adjusted Peru 5 and Peru 6 dataframes
```{r}
#Combine dataframes
p5_p6_adjusted <- bind_rows(
  p5_only %>% select(Peru3_4_5_6_ID, wave_ID, wave, session, exclude, group, gender, birthmth, birthyr, grade_2021, startdate_formatted,
                     promis_dep1:promis_dep8, promis_anx1:promis_anx4, dss1:dss20),
  p6_only %>% select(Peru3_4_5_6_ID, wave_ID, wave, session, exclude, group, gender, birthmth, birthyr, grade_2021, startdate_formatted,
                     promis_dep1:promis_dep8, promis_anx1:promis_anx4, dss1:dss20)
)

#Check new dataframe
head(p5_p6_adjusted)

#Sample size (should be N before splitting sample)
nrow(p5_p6_adjusted) #N = 6,450

#Adjust data to long format
p5_p6_adjusted <- p5_p6_adjusted %>% 
  arrange(Peru3_4_5_6_ID, group)
```